"""
db.py -- PostgreSQL (Neon) compatibility layer for HealthBridge.

The application was originally written against the stdlib ``sqlite3`` module and
spread raw SQL across nine modules. Rather than rewriting every query by hand, this
module exposes the *same* surface the rest of the code already uses::

    conn = db.connect('patients.db')
    conn.row_factory = db.Row
    cur = conn.execute('SELECT * FROM patients WHERE patient_id = ?', (pid,))
    row = cur.fetchone()
    conn.commit(); conn.close()

...but backed by psycopg3 / PostgreSQL.

What it translates for you
--------------------------
===================  =========================================================
SQLite               PostgreSQL equivalent
===================  =========================================================
``?``                ``%s`` parameter placeholders
``AUTOINCREMENT``    ``GENERATED BY DEFAULT AS IDENTITY``
``DATETIME``         ``TIMESTAMP``
``BOOLEAN DEFAULT 1``  ``BOOLEAN DEFAULT TRUE``
``INSERT OR REPLACE``  ``INSERT ... ON CONFLICT DO UPDATE SET col=EXCLUDED.col``
``ALTER ... ADD c TEXT UNIQUE``  column + ``CREATE UNIQUE INDEX IF NOT EXISTS``
``date('now','-30 days')``  ``CURRENT_DATE - INTERVAL '30 days'``
``strftime('%Y-%m', x)``      ``to_char(x, 'YYYY-MM')``
``PRAGMA ...``         ignored (no-op)
``="text"``            ``='text'``  (SQLite's double-quoted-string fallback)
``sqlite3.Row``        ``db.Row``   (dict subclass, also indexable by position)
``cursor.lastrowid``   ``RETURNING id``
===================  =========================================================

Schema mapping
--------------
The app historically used five separate SQLite files. Each one maps to its own
PostgreSQL *schema* inside the single Neon database, so existing unqualified table
names keep working via ``search_path`` and no table-name collisions occur::

    patients.db        -> schema patients
    enhanced_auth.db   -> schema enhanced_auth
    diagnosis.db       -> schema diagnosis
    fhir_data.db       -> schema fhir_data
    fhir_bundles.db    -> schema fhir_bundles

Falling back to SQLite
----------------------
If ``DATABASE_URL`` is not set (or Neon is unreachable) and ``HB_DB_BACKEND=sqlite``
is set, :func:`connect` transparently returns a real ``sqlite3`` connection instead,
so the app keeps working offline. That is how the one-time data migration reads the
legacy files.
"""

import functools
import os
import re
import sqlite3 as _sqlite3
import threading
# Aliased because ``from datetime import ... time`` below binds the *datetime.time*
# class to the name ``time`` in this namespace, which shadowed the module and left
# the connect-retry back-off calling ``datetime.time.sleep``. That raised
# AttributeError from inside the exception handler, replacing a clear
# "could not connect" error with a confusing one.
import time as _time
from datetime import date, datetime, time, timedelta

# psycopg is imported lazily on first use to avoid the ~0.1-0.2s import cost
# at module load time when running on SQLite (which is the default when
# DATABASE_URL is not set). The actual connection functions will import it
# when a PostgreSQL connection is actually requested.
_psycopg = None

def _get_psycopg():
    """Lazily import psycopg on first use."""
    global _psycopg
    if _psycopg is None:
        import psycopg
        _psycopg = psycopg
    return _psycopg

#: ``TransactionStatus.IDLE`` - i.e. no transaction currently open.
# Accessed lazily via _get_psycopg().pq.TransactionStatus.IDLE
_pg_status_idle = None

def _get_pg_status_idle():
    global _pg_status_idle
    if _pg_status_idle is None:
        _pg_status_idle = _get_psycopg().pq.TransactionStatus.IDLE
    return _pg_status_idle

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

# NOTE: these are resolved on *every* read rather than once at import time.
# ``load_dotenv()`` runs at the top of app.py, but some tools import this module
# first, and a stale empty value captured at import time would silently drop the
# whole app back to SQLite.


def _database_url():
    """The Neon connection string, read fresh each time."""
    url = os.getenv('DATABASE_URL') or os.getenv('NEON_DATABASE_URL') or ''
    # dotenv keeps trailing whitespace out of the value, but a hand-edited .env
    # often has some, and libpq would then fail to parse the URL.
    return url.strip().strip('"').strip("'")


def _force_sqlite():
    """True when explicitly asked to run on the legacy SQLite files."""
    return os.getenv('HB_DB_BACKEND', '').strip().lower() == 'sqlite'


def _int_env(name, default):
    """Read a non-negative integer from the environment, falling back on junk."""
    try:
        value = int(str(os.getenv(name, '')).strip())
    except (TypeError, ValueError):
        return default
    return value if value >= 0 else default


def _connect_kwargs():
    """Timeouts for :func:`_get_psycopg().connect`.

    Left to its own devices psycopg waits on the operating system's default
    socket timeout, which can be several minutes. A free-tier Neon instance
    that has suspended its compute, or a ``-pooler`` endpoint that is briefly
    unavailable, then shows up as an application that simply hangs with no
    output and no way to interrupt it.

    Only ``connect_timeout`` is set here. Session GUCs such as
    ``statement_timeout`` cannot be passed in the startup packet because
    PgBouncer rejects parameters it does not track ("unsupported startup
    parameter in options"); they are applied afterwards by
    :func:`_init_session` instead.
    """
    return {
        'autocommit': False,
        'connect_timeout': _int_env('HB_DB_CONNECT_TIMEOUT', 15),
    }


def _init_session(pg, schema):
    """Apply the per-connection GUCs in a single round trip.

    Every statement sent through Neon's ``-pooler`` endpoint costs a network
    round trip of roughly a second, so issuing ``SET search_path`` and the two
    timeouts one at a time tripled the cost of opening a connection - and the app
    opens five at import. The settings are independent of each other, so they are
    batched into one ``execute``; the resulting behaviour is identical.

    Deliberately no ``idle_in_transaction_session_timeout``. Behind PgBouncer the
    server-side backend is pinned to whichever client left a transaction open, so
    that timeout makes PostgreSQL kill a connection out from under the pooler
    mid-transaction, which desynchronises the client from PgBouncer and turns
    every later command on that connection into a hang.

    Set ``HB_DB_STATEMENT_TIMEOUT=0`` to skip the timeouts.
    """
    statements = [f'SET search_path TO "{schema}", public']

    statement_timeout = _int_env('HB_DB_STATEMENT_TIMEOUT', 30000)
    if statement_timeout > 0:
        # A blocked statement waits on lock_timeout, not statement_timeout, so
        # without this a row or table lock would still block indefinitely.
        statements.append(f'SET statement_timeout = {statement_timeout}')
        statements.append(f'SET lock_timeout = {min(statement_timeout, 10000)}')

    try:
        with pg.cursor() as cur:
            cur.execute('; '.join(statements))
        # Each SET opens a transaction of its own. Without this commit the
        # connection would sit idle-in-transaction from the moment it is created,
        # holding that transaction open and stalling anything needing a lock.
        pg.commit()
    except Exception:
        # An older or restricted server may refuse one of these; the others are
        # still worth having, so never let session setup fail the connection.
        try:
            pg.rollback()
        except Exception:
            pass


def __getattr__(name):
    # Keeps the old module-level constants working without caching them.
    if name == 'DATABASE_URL':
        return _database_url()
    if name == 'FORCE_SQLITE':
        return _force_sqlite()
    raise AttributeError(name)

#: SQLite filename -> PostgreSQL schema name.
SCHEMA_MAP = {
    'patients.db': 'patients',
    'enhanced_auth.db': 'enhanced_auth',
    'diagnosis.db': 'diagnosis',
    'fhir_data.db': 'fhir_data',
    'fhir_bundles.db': 'fhir_bundles',
}

DEFAULT_SCHEMA = 'public'

_created_schemas = set()
_server_version = None

#: Keys already passed to :func:`ensure_once` in this process.
_initialised_tables = set()
_init_lock = threading.Lock()


def singleton(func):
    """Decorate a zero-arg factory so its result is built once per process.

    Wraps the hand-rolled ``if x is None: x = X()`` caches that were repeated
    across the route modules, adding the two things those all lacked: a lock, so
    two threads hitting a blueprint for the first time cannot both construct the
    object and run its schema setup, and no marking-on-failure, so a constructor
    that raises does not leave a broken object cached for the life of the process.

    The attribute name on the wrapper is deliberately unhelpful so that a missed
    call site reads as an error here rather than silently working in dev and
    failing under the threaded server.
    """

    sentinel = object()
    result = sentinel
    lock = threading.Lock()

    @functools.wraps(func)
    def get():
        nonlocal result
        if result is not sentinel:
            return result
        with lock:
            if result is sentinel:
                result = func()
            return result

    return get


def ensure_once(key, setup):
    """Run ``setup`` the first time ``key`` is seen in this process.

    Every ``init_db()``/``init_database()`` in this codebase issues the same
    CREATE TABLE IF NOT EXISTS / ALTER TABLE ADD COLUMN statements, and they run
    from a constructor. Constructors here are called at import time *and* inside
    request handlers, so those idempotent statements were being re-sent over the
    wire on every start and on many individual requests - roughly a dozen round
    trips each, which on the Neon ``-pooler`` endpoint (PgBouncer in transaction
    pooling mode) cost seconds, not milliseconds. That was the entire startup
    time.

    The statements are already written to be idempotent, so running them once is
    behaviourally identical to running them every time - only the repetition goes
    away. ``key`` must identify the *table set*, not just the file: two classes
    share ``enhanced_auth.db`` and create different tables, so keying on the file
    alone would let whichever ran first suppress the other's DDL.

    Returns True when ``setup`` ran. A failure propagates and leaves ``key``
    unmarked, so the next caller retries rather than proceeding against a schema
    that was never created.
    """
    if key in _initialised_tables:
        return False
    with _init_lock:
        # Re-checked under the lock: the dev server is threaded, so two first
        # requests can arrive together.
        if key in _initialised_tables:
            return False
        setup()
        _initialised_tables.add(key)
    return True


def _schema_for(db_file):
    """Resolve a (possibly absolute) SQLite path to a PostgreSQL schema name."""
    name = os.path.basename(str(db_file))
    return SCHEMA_MAP.get(name, DEFAULT_SCHEMA)


# --------------------------------------------------------------------------- #
# Exceptions
# --------------------------------------------------------------------------- #
# These names ARE the stdlib ones, deliberately, rather than a parallel hierarchy
# that happens to share a spelling.
#
# The codebase catches ``db.OperationalError`` to mean "the object already exists"
# and ``db.IntegrityError`` to mean "duplicate key". On PostgreSQL those catches
# receive the errors :func:`_translate_error` re-raises, so they need the db names.
# On SQLite the driver raises its own exceptions, which those same catches do not
# recognise - so every idempotent ``ALTER TABLE ... ADD COLUMN`` guard escaped its
# handler and took the boot down with it.
#
# Subclassing cannot fix that: ``except db.X`` matches subclasses of ``db.X``, and
# sqlite3 has already built its exceptions by the time we get a say, so
# ``sqlite3.OperationalError`` will never be an instance of some subclass of ours.
# Aliasing is the only thing that makes one name denote one type, which is what
# lets a single except-clause catch a translated PostgreSQL error and a native
# SQLite one alike.
#
# sqlite3's own hierarchy already matches what is needed:
#   Error <- DatabaseError <- {OperationalError, IntegrityError, DataError}
# so aliasing preserves the parent/child relationships :func:`_translate_error` and
# its SQLSTATE map rely on.

Error = _sqlite3.Error
DatabaseError = _sqlite3.DatabaseError
OperationalError = _sqlite3.OperationalError
IntegrityError = _sqlite3.IntegrityError
DataError = _sqlite3.DataError


_SQLSTATE_MAP = {
    '42701': OperationalError,   # duplicate_column
    '42703': OperationalError,   # undefined_column
    '42P01': OperationalError,   # undefined_table
    '42P07': OperationalError,   # duplicate_table
    '42P06': OperationalError,   # duplicate_schema
    '42501': OperationalError,   # insufficient_privilege
    '22001': DataError,          # string_data_right_truncation
    '22P02': DataError,          # invalid_text_representation
    '22003': DataError,          # numeric_value_out_of_range
    '22007': DataError,          # invalid_datetime_format
    '22008': DataError,          # datetime_field_overflow
    '22012': DataError,          # division_by_zero
}


def _translate_error(exc):
    """Re-raise a psycopg error under a sqlite3-compatible name."""
    sqlstate = getattr(exc, 'sqlstate', None) or ''
    if sqlstate.startswith('23'):
        cls = IntegrityError
    else:
        cls = _SQLSTATE_MAP.get(sqlstate, DatabaseError)
    return cls(f'{sqlstate}: {exc}').with_traceback(exc.__traceback__)


# --------------------------------------------------------------------------- #
# SQL translation
# --------------------------------------------------------------------------- #

def _split_literals(sql):
    """Yield (is_literal, chunk) so we can rewrite only real SQL, not strings.

    Protects single-quoted strings, double-quoted identifiers, ``--`` line
    comments and ``/* */`` block comments from the token rewrites below.
    """
    i, n = 0, len(sql)
    buf = []
    while i < n:
        ch = sql[i]
        if ch == "'":
            j = i + 1
            while j < n:
                if sql[j] == "'":
                    if j + 1 < n and sql[j + 1] == "'":
                        j += 2
                        continue
                    j += 1
                    break
                j += 1
            buf.append((True, sql[i:j]))
            i = j
        elif ch == '"':
            j = sql.find('"', i + 1)
            j = n if j == -1 else j + 1
            buf.append((True, sql[i:j]))
            i = j
        elif ch == '-' and sql.startswith('--', i):
            j = sql.find('\n', i)
            j = n if j == -1 else j
            buf.append((True, sql[i:j]))
            i = j
        elif ch == '/' and sql.startswith('/*', i):
            j = sql.find('*/', i + 2)
            j = n if j == -1 else j + 2
            buf.append((True, sql[i:j]))
            i = j
        else:
            buf.append((False, ch))
            i += 1
    return buf


def _join(chunks):
    return ''.join(text for _, text in chunks)


def _map_outside_literals(chunks, fn):
    return [(is_lit, fn(text) if not is_lit else text) for is_lit, text in chunks]


_STRFTIME_RE = re.compile(r"strftime\s*\(\s*'([^']*)'\s*", re.IGNORECASE)
_DATE_NOW_RE = re.compile(r"date\s*\(\s*'now'\s*(?:,\s*'([^']*)'\s*)?\)", re.IGNORECASE)
_INTERVAL_UNITS = {
    'day': 'days', 'days': 'days',
    'week': 'weeks', 'weeks': 'weeks',
    'month': 'months', 'months': 'months',
    'year': 'years', 'years': 'years',
    'hour': 'hours', 'hours': 'hours',
    'minute': 'minutes', 'minutes': 'minutes',
    'second': 'seconds', 'seconds': 'seconds',
}

_STRFTIME_MAP = [
    ('%Y', 'YYYY'), ('%m', 'MM'), ('%d', 'DD'),
    ('%H', 'HH24'), ('%M', 'MI'), ('%S', 'SS'),
    ('%y', 'YY'), ('%j', 'DDD'), ('%W', 'WW'),
]


def _to_pg_timestamp_format(fmt):
    for src, dst in _STRFTIME_MAP:
        fmt = fmt.replace(src, dst)
    return fmt


def _date_now_repl(m):
    modifier = m.group(1)
    if not modifier:
        return 'CURRENT_DATE'
    mm = re.match(r'\s*([+-]?\d+)\s+([a-z]+)\s*$', modifier.strip())
    if not mm:
        return 'CURRENT_DATE'
    amount, unit = mm.group(1), _INTERVAL_UNITS.get(mm.group(2).lower())
    if not unit:
        return 'CURRENT_DATE'
    return f"CURRENT_DATE - INTERVAL '{amount.lstrip('+-')} {unit}'"


def _rewrite_insert_or_replace(sql):
    """``INSERT OR REPLACE INTO t (a,b) VALUES (?,?)`` -> INSERT ... ON CONFLICT DO UPDATE."""
    m = re.match(
        r'(\s*INSERT\s+OR\s+REPLACE\s+INTO\s+([\w".]+)\s*\(([^)]*)\)\s*VALUES\s*\()',
        sql, re.IGNORECASE | re.DOTALL)
    if not m:
        return sql

    head, col_list = m.group(1), m.group(3)
    tail = sql[m.end():]                      # everything after "VALUES ("
    cols = [c.strip().strip('"') for c in col_list.split(',') if c.strip()]
    assignments = ', '.join(f'"{c}" = EXCLUDED."{c}"' for c in cols)
    rewritten = re.sub(r'INSERT\s+OR\s+REPLACE', 'INSERT', head, flags=re.IGNORECASE) + tail

    stripped = rewritten.rstrip()
    if stripped.endswith(';'):
        stripped = stripped[:-1].rstrip()
    return f'{stripped} ON CONFLICT DO UPDATE SET {assignments};'


def _rewrite_alter_add_column(sql):
    """``ALTER TABLE t ADD COLUMN c TEXT UNIQUE`` -> two statements (PG forbids UNIQUE here)."""
    m = re.match(
        r'\s*ALTER\s+TABLE\s+([\w".]+)\s+ADD\s+COLUMN\s+([\w"]+)\s+(.*?);?\s*$',
        sql, re.IGNORECASE | re.DOTALL)
    if not m:
        return sql

    table, column, rest = m.group(1), m.group(2).strip('"'), m.group(3).rstrip(' ;')
    unique = bool(re.search(r'\bUNIQUE\b', rest, re.IGNORECASE))
    rest_clean = re.sub(r'\bUNIQUE\b', '', rest, flags=re.IGNORECASE).strip()

    statement = f'ALTER TABLE {table} ADD COLUMN {column} {rest_clean};'
    if unique:
        bare = table.replace('"', '')
        idx = f'idx_{bare}_{column}'.lower().replace('.', '_')
        statement += (
            f' CREATE UNIQUE INDEX IF NOT EXISTS {idx} ON {table} ({column});'
        )
    return statement


def translate_sql(sql, boolean_columns=(), schema=None, tables=()):
    """Rewrite SQLite-flavoured SQL into PostgreSQL-flavoured SQL.

    ``boolean_columns`` is the set of column names that are real ``BOOLEAN``
    columns in the target schema. SQLite has no boolean type - it stores 0/1 and
    happily compares a flag column against the integer 1 - so those comparisons
    have to become ``= TRUE`` / ``= FALSE`` or PostgreSQL rejects them with
    ``operator does not exist: boolean = integer``.

    ``schema``/``tables`` enable schema-qualification of every table reference.
    That is deliberate: the Neon connection string uses the ``-pooler`` host,
    which is PgBouncer in *transaction* pooling mode. A session-level
    ``SET search_path`` is only reliable inside a single transaction, because
    PgBouncer may hand the next transaction to a different backend server.
    Qualifying names explicitly makes the SQL correct no matter which backend
    ends up serving it.
    """
    if not sql:
        return sql

    stripped = sql.strip()

    # PRAGMA has no PostgreSQL equivalent and is always advisory here.
    if re.match(r'\s*PRAGMA\b', stripped, re.IGNORECASE):
        return 'SELECT 1'

    if re.match(r'\s*INSERT\s+OR\s+REPLACE\b', stripped, re.IGNORECASE):
        # NOTE: no ? -> %s pass here, so translate the body too.
        return _rewrite_insert_or_replace(
            stripped.replace('?', '%s') if '?' in stripped else stripped)

    if re.match(r'\s*ALTER\s+TABLE\b', stripped, re.IGNORECASE):
        # NOTE: no early return here. The rewritten ALTER still needs its target
        # schema-qualified - returning early sent it through search_path instead,
        # so "ALTER TABLE fhir_bundles ADD COLUMN ..." silently altered whichever
        # schema the pooled connection happened to be pointing at, which put
        # fhir_interop's upload_date column onto an unrelated table.
        sql = _rewrite_alter_add_column(stripped)

    # These constructs quote their own arguments, so they must run against the raw
    # SQL - the literal-aware pass below deliberately skips anything inside quotes.
    sql = _DATE_NOW_RE.sub(_date_now_repl, sql)
    sql = _rewrite_strftime_calls(sql)

    # SQLite's double-quoted-string fallback: role = "patient" -> role = 'patient'
    # (in PostgreSQL a double-quoted token is an identifier, not a value)
    sql = re.sub(r'=\s*"([^"]*)"', r"= '\1'", sql)

    if boolean_columns:
        sql = _rewrite_boolean_literals(sql, boolean_columns)

    if schema and tables:
        sql = _qualify_tables(sql, schema, tables)

    # CREATE/DROP TABLE targets are qualified unconditionally (see
    # _qualify_ddl_tables), because a brand-new table is not in ``tables`` yet
    # and would otherwise be created in whatever search_path happens to point at.
    if schema:
        sql = _qualify_ddl_tables(sql, schema)

    chunks = _split_literals(sql)

    # ? -> %s
    chunks = _map_outside_literals(chunks, lambda t: t.replace('?', '%s'))

    sql = _join(chunks)

    # Type / default keyword fixes.
    sql = re.sub(
        r'\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b',
        'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        sql, flags=re.IGNORECASE)
    sql = re.sub(r'\bDATETIME\b', 'TIMESTAMP', sql, flags=re.IGNORECASE)
    sql = re.sub(r'\bBOOLEAN\s+DEFAULT\s+1\b', 'BOOLEAN DEFAULT TRUE', sql, flags=re.IGNORECASE)
    sql = re.sub(r'\bBOOLEAN\s+DEFAULT\s+0\b', 'BOOLEAN DEFAULT FALSE', sql, flags=re.IGNORECASE)

    return sql


# Keywords after which a bare table name is expected.
# ``REFERENCES`` is included so foreign-key targets in CREATE TABLE resolve in
# the right schema too, not just via search_path.
#
# The identifier must also match double-quoted names ("patients"): several call
# sites - migrate_sqlite_to_neon.py among them - quote the table name, and an
# unquoted-only pattern silently skipped those, leaving them to be resolved via
# search_path. Under the -pooler host (PgBouncer in transaction pooling mode)
# search_path is not preserved between transactions, so those statements failed
# intermittently with 42P01 "relation does not exist".
#
# An optional trailing ".ident" is captured so already-qualified references
# ("s"."t" / public.t) can be recognised and left alone rather than being
# qualified a second time.
_IDENT = r'(?:"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)'
_TABLE_REF_RE = re.compile(
    r'\b(FROM|JOIN|INTO|UPDATE|REFERENCES)\s+(' + _IDENT + r'(?:\s*\.\s*' + _IDENT + r')?)',
    re.IGNORECASE,
)


def _unqualify(name):
    """Strip quotes and any schema prefix from a table reference."""
    return name.replace('"', '').split('.')[-1].lower()


def _qualify_tables(sql, schema, tables):
    """Prefix bare table references with their schema.

    Only rewrites names that are actually tables in ``tables``, so CTE names,
    subquery aliases and column names are left alone.
    """
    known = set(tables)
    if not known:
        return sql

    def repl(m):
        keyword, name = m.group(1), m.group(2)
        # Already schema-qualified - qualifying again yields an invalid
        # three-part name ("s"."t"."t").
        if '.' in name:
            return m.group(0)
        # A CTE name or subquery alias, not a real table.
        if _unqualify(name) not in known:
            return m.group(0)
        # Double-quote a bare name so mixed-case tables keep resolving.
        quoted = name if name.startswith('"') else f'"{name}"'
        return f'{keyword} "{schema}".{quoted}'

    return _TABLE_REF_RE.sub(repl, sql)


# CREATE TABLE / DROP TABLE / ALTER TABLE carry no FROM/INTO keyword, so they
# need their own pattern. Unlike a SELECT target, a DDL target is unambiguously a
# real table - never a CTE name or alias - so it is qualified *unconditionally*.
# Without this, a table created before it exists in ``tables`` would fall back to
# search_path, and could silently land in ``public`` instead of its own schema.
# A possibly schema-qualified identifier: one segment, or segments joined by
# dots where each may be bare or double-quoted. Matching the *whole* qualified
# name matters - a pattern that only captures a single quoted identifier turns
# 'ALTER TABLE "s"."t"' into '"wrong"."s"."t"', because the trailing ".t" is
# then left outside the match and the captured half looks unqualified.
_IDENT = r'(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$]*)'
_QUALIFIED_IDENT = _IDENT + r'(?:\.' + _IDENT + r')*'

_CREATE_TABLE_RE = re.compile(
    r'\b(?P<head>(?:CREATE|DROP|ALTER)\s+TABLE)'
    r'(?P<exists>\s+IF\s+(?:NOT\s+)?EXISTS)?'
    r'(?P<only>\s+ONLY)?'
    r'\s+(?P<name>' + _QUALIFIED_IDENT + r')',
    re.IGNORECASE,
)


def _qualify_ddl_tables(sql, schema):
    """Schema-qualify CREATE/DROP/ALTER TABLE targets.

    Without this they fall back to ``search_path``, which the ``-pooler`` host
    (PgBouncer, transaction pooling) does not preserve between transactions.
    """

    def quote(name):
        """Double-quote a bare identifier; leave an already-quoted one alone."""
        return name if name.startswith('"') else f'"{name}"'

    def table_repl(m):
        name = m.group('name')
        # Already carries a schema prefix.
        if '.' in name:
            return m.group(0)
        head = f'{m.group("head")}{m.group("exists") or ""}{m.group("only") or ""}'
        return f'{head} "{schema}".{quote(name)}'

    def index_repl(m):
        name = m.group('name')
        if '.' in name:
            return m.group(0)
        return f'{m.group("head")} ON "{schema}".{quote(name)}'

    sql = _CREATE_TABLE_RE.sub(table_repl, sql)
    sql = _CREATE_INDEX_RE.sub(index_repl, sql)
    return _add_column_guard(sql)


# ``ALTER TABLE t ADD COLUMN c ...`` with no IF NOT EXISTS.
_ADD_COLUMN_RE = re.compile(
    r'(?P<head>\bALTER\s+TABLE\s+(?:ONLY\s+)?[\w".]+(?:\s+ADD\s+COLUMN)\s+)(?!IF\b)',
    re.IGNORECASE,
)

# Patterns used to keep the cached catalog lookups in step with executed DDL.
# The schema qualifier is optional because the translator emits qualified names,
# e.g. CREATE TABLE IF NOT EXISTS "patients"."patients".
_CREATE_TABLE_NAME_RE = re.compile(
    r'^\s*CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?'
    r'(?:"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)\s*\.\s*'
    r'(?:"(?P<name>[^"]+)"|(?P<bare>[A-Za-z_][A-Za-z0-9_]*))',
    re.IGNORECASE,
)
_CREATE_TABLE_NAME_UNQUALIFIED_RE = re.compile(
    r'^\s*CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?'
    r'(?:"(?P<name>[^"]+)"|(?P<bare>[A-Za-z_][A-Za-z0-9_]*))',
    re.IGNORECASE,
)
_ADD_COLUMN_NAME_RE = re.compile(
    r'^\s*ALTER\s+TABLE\s+(?:ONLY\s+)?[\w".]+\s+ADD\s+COLUMN\s+(?:IF\s+NOT\s+EXISTS\s+)?'
    r'(?:"(?P<name>[^"]+)"|(?P<bare>[A-Za-z_][A-Za-z0-9_]*))\s+(?P<type>[A-Za-z ]+)',
    re.IGNORECASE,
)

# Only statements carrying their own no-op guard may be skipped.
_IF_NOT_EXISTS_RE = re.compile(r'IF\s+NOT\s+EXISTS', re.IGNORECASE)

_CREATE_INDEX_NAME_RE = re.compile(
    r'^\s*CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?'
    r'(?:"(?P<name>[^"]+)"|(?P<bare>[A-Za-z_][A-Za-z0-9_]*))',
    re.IGNORECASE,
)

_ALTER_TARGET_TABLE_RE = re.compile(
    r'^\s*ALTER\s+TABLE\s+(?:ONLY\s+)?'
    r'(?:"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)\s*\.\s*'
    r'(?:"(?P<name>[^"]+)"|(?P<bare>[A-Za-z_][A-Za-z0-9_]*))',
    re.IGNORECASE,
)
_ALTER_TARGET_TABLE_UNQUALIFIED_RE = re.compile(
    r'^\s*ALTER\s+TABLE\s+(?:ONLY\s+)?'
    r'(?:"(?P<name>[^"]+)"|(?P<bare>[A-Za-z_][A-Za-z0-9_]*))',
    re.IGNORECASE,
)


def _alter_target_table(sql):
    """The lower-cased table an ``ALTER TABLE`` targets, or '' if unclear."""
    match = _ALTER_TARGET_TABLE_RE.match(sql) or _ALTER_TARGET_TABLE_UNQUALIFIED_RE.match(sql)
    return ((match.group('name') or match.group('bare') or '').lower()) if match else ''


def _add_column_guard(sql):
    """Add ``IF NOT EXISTS`` to ``ALTER TABLE ... ADD COLUMN``.

    Every ``init_db()`` in this codebase adds its extra columns with a bare
    ``ADD COLUMN`` wrapped in ``try/except OperationalError``, relying on the
    duplicate-column error as the "does it already exist" test. On PostgreSQL
    that costs a wasted statement and an aborted transaction every single start,
    which in turn forces the savepoint dance in ``Connection._execute_once``.

    PostgreSQL has native support for the guard, so supply it here. This only
    affects translated (PostgreSQL) statements - the SQLite fallback path does
    not go through the translator at all.
    """
    return _ADD_COLUMN_RE.sub(lambda m: m.group('head') + 'IF NOT EXISTS ', sql)


# ``ALTER TABLE ... ADD COLUMN c UNIQUE`` is rewritten into a companion
# CREATE UNIQUE INDEX, whose ON <table> target would otherwise be unqualified and
# so resolve through search_path.
_CREATE_INDEX_RE = re.compile(
    r'\b(?P<head>CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?IF\s+NOT\s+EXISTS\s+'
    r'(?P<idx>"[^"]+"|[A-Za-z_][A-Za-z0-9_]*))\s+ON\s+'
    r'(?P<name>' + _QUALIFIED_IDENT + r')',
    re.IGNORECASE,
)


def _rewrite_boolean_literals(sql, boolean_columns):
    """Rewrite ``flag_col = 1`` / ``= 0`` into ``= TRUE`` / ``= FALSE``."""
    names = sorted((c for c in boolean_columns if c), key=len, reverse=True)
    if not names:
        return sql
    pattern = re.compile(
        r'\b(' + '|'.join(re.escape(n) for n in names) + r')\s*=\s*([01])\b',
        re.IGNORECASE,
    )
    return pattern.sub(lambda m: f'{m.group(1)} = {"TRUE" if m.group(2) == "1" else "FALSE"}', sql)


def _rewrite_strftime_calls(sql):
    out = []
    i = 0
    while True:
        m = _STRFTIME_RE.search(sql, i)
        if not m:
            out.append(sql[i:])
            break

        out.append(sql[i:m.start()])

        # The regex already consumed strftime('fmt' - find the matching ')' for it.
        depth = 1
        j = m.end()
        while j < len(sql) and depth:
            if sql[j] == '(':
                depth += 1
            elif sql[j] == ')':
                depth -= 1
            j += 1

        fmt = m.group(1).strip()
        # Remaining args, i.e. everything the regex did not eat.
        rest = sql[m.end():j - 1].lstrip()
        if rest.startswith(','):
            rest = rest[1:].strip()

        out.append(f"to_char({rest}, '{_to_pg_timestamp_format(fmt)}')")
        i = j
    return ''.join(out)


# --------------------------------------------------------------------------- #
# Row
# --------------------------------------------------------------------------- #

class Row(dict):
    """dict subclass that also supports positional access, like sqlite3.Row.

    Built two ways, because ``row_factory`` is handed a row under two different
    conventions. sqlite3 invokes a factory as ``factory(cursor, row)``, which is
    what happens when ``HB_DB_BACKEND=sqlite`` and :func:`connect` returns a genuine
    sqlite3 connection. :meth:`Cursor._coerce` builds the mapping form directly on
    the PostgreSQL path. Supporting only the second made every
    ``conn.row_factory = db.Row`` line in the codebase raise
    ``TypeError: dict expected at most 1 argument, got 2`` as soon as the app was run
    on SQLite.
    """

    __slots__ = ()

    def __new__(cls, *args, **kwargs):
        # dict.__new__ discards whatever it is handed - the contents are applied by
        # __init__, which type.__call__ invokes with the same arguments. So the
        # factory form has to be recognised there, not here.
        return dict.__new__(cls)

    def __init__(self, *args, **kwargs):
        if len(args) == 2 and hasattr(args[0], 'description'):
            dict.update(self, zip(_column_names(args[0].description), args[1]))
        else:
            dict.update(self, *args, **kwargs)

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return dict.__getitem__(self, key)


def _normalise(value):
    """Return date/time values as ISO strings so downstream slicing keeps working.

    sqlite3 handed back raw TEXT for DATETIME columns, and lots of templates do
    ``created_at[:10]`` / ``uploaded_at[:16]``. psycopg would hand back real
    datetime objects, so convert back to strings to preserve that behaviour.
    """
    if isinstance(value, (datetime, date, time)):
        return value.isoformat()
    if isinstance(value, timedelta):
        return value.total_seconds()
    return value


def _column_names(desc):
    """Column names from a cursor description, whichever backend produced it.

    A sqlite3 description is a plain 7-tuple per column, so the name is at index 0.
    psycopg leaves those legacy tuple slots empty and exposes ``.name`` instead.
    Reading the index first and falling back covers both without the caller having
    to know which connection it is holding.
    """
    names = []
    for column in desc:
        name = column[0] if column else None
        names.append(name if name else column.name)
    return names


# --------------------------------------------------------------------------- #
# Cursor / Connection
# --------------------------------------------------------------------------- #

_INSERT_RE = re.compile(r'^\s*INSERT\s+INTO\s+([\w".]+)', re.IGNORECASE)
_DDL_RE = re.compile(r'^\s*(CREATE|ALTER|DROP)\b', re.IGNORECASE)

# DDL that cannot change the set of tables or their columns, so it must not
# invalidate the cached catalog lookups.
_INDEX_OR_SCHEMA_RE = re.compile(
    r'^\s*(?:CREATE|DROP)\s+(?:OR\s+REPLACE\s+)?'
    r'(?:UNIQUE\s+)?(?:INDEX|SCHEMA|SEQUENCE|EXTENSION)\b',
    re.IGNORECASE,
)

# Statements that are safe to replay after a reconnect.
_READ_ONLY_RE = re.compile(r'^\s*(SELECT|WITH|SHOW|EXPLAIN)\b', re.IGNORECASE)

# DDL that is safe to replay: the statement declares its own no-op behaviour,
# so running it twice leaves the schema exactly as running it once would. The
# guarded forms are the point - a bare "CREATE TABLE t" must never be retried,
# because the first attempt may well have succeeded before the socket died.
_IDEMPOTENT_DDL_RE = re.compile(
    r'^\s*(?:'
    r'CREATE\s+(?:OR\s+REPLACE\s+)?'
    r'(?:TABLE|INDEX|VIEW|MATERIALIZED\s+VIEW|SEQUENCE|SCHEMA|FUNCTION|TRIGGER)'
    r'(?:\s+IF\s+NOT\s+EXISTS)?\b'
    r'|DROP\s+(?:TABLE|INDEX|VIEW|MATERIALIZED\s+VIEW|SEQUENCE|SCHEMA|FUNCTION|TRIGGER)'
    r'(?:\s+IF\s+EXISTS|\s+CASCADE|\s+RESTRICT)?\b'
    r'|ALTER\s+TABLE\s+[\w".]+\s+ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS\b'
    r')',
    re.IGNORECASE,
)

# SQLSTATEs meaning the server or the transport went away.
_CONN_LOST_SQLSTATES = frozenset({
    '08000',  # connection_exception
    '08001',  # sqlclient_unable_to_establish_sqlconnection
    '08003',  # connection_does_not_exist
    '08004',  # sqlserver_rejected_establishment_of_sqlconnection
    '08006',  # connection_failure
    '08007',  # transaction_resolution_unknown
    '08P01',  # protocol_violation
    '53300',  # too_many_connections
    '57P01',  # admin_shutdown
    '57P02',  # crash_shutdown
    '57P03',  # cannot_connect_now
})


def _is_connection_lost(exc):
    """True when ``exc`` means the connection to the server went away.

    ``Connection.execute`` re-raises psycopg errors through :func:`_translate_error`
    as HealthBridge ``DatabaseError`` subclasses, which carry no SQLSTATE of their
    own - so both the wrapper and its ``__cause__`` are inspected. psycopg also
    surfaces some of these only in the message text ("the connection is lost",
    "server closed the connection unexpectedly"), hence the substring check.
    """
    needles = (
        'connection is lost',
        'connection already closed',
        'server closed the connection',
        'terminating connection',
        'consuming input failed',
        'connection timeout expired',
        'ssl connection has been closed',
    )
    for err in (exc, getattr(exc, '__cause__', None)):
        if err is None:
            continue
        if getattr(err, 'sqlstate', None) in _CONN_LOST_SQLSTATES:
            return True
        msg = str(err).lower()
        if any(needle in msg for needle in needles):
            return True
    return False


class Cursor:
    """Wraps a psycopg cursor, adding ``lastrowid`` and sqlite-ish row factories.

    ``cur`` may be ``None`` for a statement that was answered from the schema
    cache instead of being sent to the server; the fetch methods then behave like
    an exhausted cursor, which is what such a no-op statement would return.
    """

    def __init__(self, connection, cur, raw_sql):
        self._conn = connection
        self._cur = cur
        self._raw_sql = raw_sql
        self.lastrowid = None
        self.rowcount = -1
        self.description = None
        self.arraysize = 1

    # -- iteration / fetching ------------------------------------------------
    def fetchone(self):
        if self._cur is None:
            return None
        row = self._cur.fetchone()
        return self._coerce(row)

    def fetchmany(self, size=None):
        if self._cur is None:
            return []
        rows = self._cur.fetchmany(size) if size is not None else self._cur.fetchmany()
        return [self._coerce(r) for r in rows]

    def fetchall(self):
        if self._cur is None:
            return []
        rows = self._cur.fetchall()
        return [self._coerce(r) for r in rows]

    def __iter__(self):
        if self._cur is None:
            return iter(())
        for row in self._cur:
            yield self._coerce(row)

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
        return False

    def close(self):
        try:
            self._cur.close()
        except Exception:
            pass

    # -- passthrough ---------------------------------------------------------
    def __getattr__(self, name):
        return getattr(self._cur, name)

    def _coerce(self, row):
        """psycopg returns tuples; wrap them in Row when row_factory is set."""
        if self._conn.row_factory is Row and row is not None:
            names = [d.name for d in (self._cur.description or [])]
            return Row({n: _normalise(v) for n, v in zip(names, row)})
        if self._conn.row_factory is None and row is not None:
            return tuple(_normalise(v) for v in row)
        return row


class RawCursor:
    """DBAPI cursor wrapper that runs statements through the SQL translator.

    :meth:`Connection.execute` returns a :class:`Cursor`, but callers such as
    ``pandas.read_sql_query`` obtain a cursor directly and drive ``execute``
    themselves. Those statements have to be translated too, or bare table names
    are resolved via ``search_path``.
    """

    def __init__(self, connection, cur):
        self._conn = connection
        self._cur = cur

    def execute(self, sql, parameters=None, **kwargs):
        translated = translate_sql(
            sql,
            self._conn._boolean_columns(),
            schema=self._conn.schema,
            tables=self._conn._tables(),
        )
        with self._conn._lock:
            self._cur.execute(translated, list(parameters) if parameters else None)
        return self

    def executemany(self, sql, seq_of_params):
        for params in seq_of_params:
            self.execute(sql, params)
        return self

    # -- introspection used by pandas ---------------------------------------
    @property
    def description(self):
        return self._cur.description

    @property
    def rowcount(self):
        return self._cur.rowcount

    @property
    def rownumber(self):
        return self._cur.rownumber

    @property
    def connection(self):
        return self._conn

    def fetchone(self):
        return self._cur.fetchone()

    def fetchmany(self, size=None):
        return self._cur.fetchmany(size) if size is not None else self._cur.fetchmany()

    def fetchall(self):
        return self._cur.fetchall()

    def nextset(self):
        return self._cur.nextset()

    def setinputsizes(self, sizes):
        return self._cur.setinputsizes(sizes)

    def setoutputsize(self, size, column=None):
        return self._cur.setoutputsize(size, column)

    def close(self):
        try:
            self._cur.close()
        except Exception:
            pass

    def __iter__(self):
        return iter(self._cur)

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
        return False

    def __getattr__(self, name):
        return getattr(self._cur, name)


class Connection:
    """DBAPI-ish connection bound to one PostgreSQL schema."""

    def __init__(self, dsn, schema):
        self.schema = schema
        self.row_factory = None
        self._shared = False
        self._id_columns = {}
        self._bool_cols = None
        self._all_cols = None
        self._index_names = None
        self._table_names = None
        self._lock = threading.RLock()
        self._dsn = dsn
        self._ensure_schema(dsn, schema)
        self._pg = _get_psycopg().connect(dsn, **_connect_kwargs())
        # Kept as a convenience for ad-hoc queries, but the SQL translator
        # schema-qualifies every table reference, because PgBouncer transaction
        # pooling does not reliably preserve this setting between transactions.
        _init_session(self._pg, schema)

    def _note_ddl(self, sql):
        """Keep the cached catalog lookups in step with a DDL statement.

        The guarded forms this codebase actually issues -
        ``CREATE TABLE IF NOT EXISTS`` and ``ADD COLUMN IF NOT EXISTS`` - have a
        predictable effect on the cached metadata, so the caches can be updated
        in place instead of dropped. Anything else (a bare CREATE/DROP, an
        unexpected form) falls back to a full invalidation, which is always
        correct, merely slower.

        Note this is best-effort bookkeeping: if a statement fails, the caller
        re-raises and the process usually stops anyway, and the worst case for a
        wrong guess is one stale entry that a later ``CREATE TABLE`` would
        surface as "already exists".
        """
        statement = sql.strip()

        # CREATE INDEX / DROP INDEX / CREATE SCHEMA never change the set of
        # tables or their columns, so those caches are still accurate - but the
        # index set itself does change, so refresh just that one.
        if _INDEX_OR_SCHEMA_RE.match(statement):
            if re.match(r'^\s*(?:CREATE|DROP)\s+(?:OR\s+REPLACE\s+)?(?:UNIQUE\s+)?INDEX\b',
                        statement, re.IGNORECASE):
                self._index_names = None
            return

        match = _CREATE_TABLE_NAME_RE.match(statement) or _CREATE_TABLE_NAME_UNQUALIFIED_RE.match(statement)
        if match:
            name = (match.group('name') or match.group('bare') or '').lower()
            if name:
                if self._table_names is not None:
                    self._table_names.add(name)
                # A brand-new table has no columns yet, and the CREATE body in
                # this codebase is not parsed here, so drop just that entry.
                if self._all_cols is not None:
                    self._all_cols.pop(name, None)
                self._id_columns.pop(name, None)
            return

        match = _ADD_COLUMN_NAME_RE.match(statement)
        if match:
            name = (match.group('name') or match.group('bare') or '')
            declared = (match.group('type') or '').strip().upper()
            table = _alter_target_table(statement)
            # Only the BOOLEAN set is cached, so a column of any other type
            # cannot make _bool_cols stale. ADD COLUMN never changes whether a
            # table has an "id" column, so _id_columns stays valid too.
            if name and declared.startswith('BOOL') and self._bool_cols is not None:
                self._bool_cols.add(name)
            if name and table and self._all_cols is not None:
                self._all_cols.setdefault(table, set()).add(name.lower())
            return

        # DROP TABLE, or anything we cannot model: be conservative.
        self._bool_cols = None
        self._all_cols = None
        self._index_names = None
        self._table_names = None
        self._id_columns.clear()

    def _reconnect(self):
        """Replace the underlying connection after the server dropped it.

        Neon's ``-pooler`` endpoint recycles server-side connections, so a
        long-lived pooled connection can die between statements. psycopg does not
        necessarily mark that as closed - ``transaction_status`` still reports
        IDLE because nothing touched the wire - so the health check in
        :func:`_acquire` cannot see it and the next statement fails with
        "the connection is lost". Rebuilding the socket here, and retrying the
        statement once, turns a hard error into a transparent reconnect.
        """
        try:
            self._pg.close()
        except Exception:
            pass
        self._pg = _get_psycopg().connect(self._dsn, **_connect_kwargs())
        _init_session(self._pg, self.schema)
        # Column/table metadata may differ on the new backend session.
        self._bool_cols = None
        self._all_cols = None
        self._index_names = None
        self._table_names = None
        self._id_columns.clear()

    # -- lifecycle ----------------------------------------------------------
    def commit(self):
        with self._lock:
            self._pg.commit()

    def rollback(self):
        with self._lock:
            self._pg.rollback()

    def close(self):
        """Close the connection, unless it is a shared one from the cache."""
        if getattr(self, '_shared', False):
            _release(self.schema, self)
            return
        try:
            self._pg.close()
        except Exception:
            pass

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
        return False

    # -- execution ----------------------------------------------------------
    def execute(self, sql, parameters=None):
        """Run one statement, transparently reconnecting if the server dropped us."""
        try:
            return self._execute_once(sql, parameters)
        except Exception as exc:
            # Replay only what is safe to run twice. A read-only statement cannot
            # change anything, and the guarded DDL forms are no-ops when the
            # object already exists. A plain INSERT/UPDATE/DELETE, or DDL
            # without an IF [NOT] EXISTS guard, is surfaced instead: if such a
            # statement lost its connection there is no way to know whether the
            # server applied it first, so retrying could duplicate the row.
            statement = sql.strip()
            replayable = _READ_ONLY_RE.match(statement) or _IDEMPOTENT_DDL_RE.match(statement)
            if not (_is_connection_lost(exc) and replayable):
                raise
            try:
                self._reconnect()
            except Exception:
                raise exc
            return self._execute_once(sql, parameters)

    def _execute_once(self, sql, parameters=None):
        translated = translate_sql(
            sql,
            self._boolean_columns(),
            schema=self.schema,
            tables=self._tables(),
        )
        params = list(parameters) if parameters else None

        translated, params, want_id = self._prepare_insert(translated, params)

        is_ddl = bool(_DDL_RE.match(translated))

        # A guarded CREATE/ALTER/INDEX that the catalog shows is already satisfied
        # is a guaranteed no-op. Answering it from the cache instead of sending it
        # keeps the ~45 such statements the app issues at import off the wire,
        # where each costs about a second through Neon's pooler - that alone was
        # over a hundred seconds of startup. The check runs on the *translated*
        # statement, because that is where the translator has added the
        # ``IF NOT EXISTS`` guard and schema-qualified the names.
        # ``_all_statements_noop`` returns False unless every part is certain, so
        # this can only ever skip work that would have changed nothing.
        if is_ddl and not params:
            try:
                if self._all_statements_noop(translated):
                    return Cursor(self, None, sql)
            except Exception:
                # Never let the optimisation itself break a statement; fall
                # through and let the server be the judge.
                pass

        # DDL can introduce or drop tables/columns, so the cached catalog
        # lookups can go stale. Blanket-invalidating them here is correct but
        # ruinously slow: every init_db() issues dozens of CREATE TABLE IF NOT
        # EXISTS / ADD COLUMN IF NOT EXISTS statements, and each invalidation
        # forces the *next* statement to re-query information_schema. Behind
        # Neon's pooler a round trip costs about a second, so the app spent well
        # over a hundred seconds at import re-reading a catalog that had not
        # actually changed. Update the caches from the statement text instead,
        # and only fall back to a full invalidation for DDL we cannot model.
        if is_ddl:
            self._note_ddl(translated)

        # Set when a failed DDL statement has already been rolled back to its
        # savepoint, which leaves the transaction usable - see below.
        savepoint_restored = False

        try:
            # Shared connections are used from Flask's threaded dev server, and
            # a psycopg connection cannot interleave two operations.
            with self._lock:
                cur = self._pg.cursor()
                if is_ddl:
                    # init_db()/init_database() run a CREATE TABLE immediately
                    # followed by an "ADD COLUMN if it doesn't exist" probe that
                    # is *expected* to fail. In SQLite a failed statement leaves
                    # earlier work in the transaction intact, but in PostgreSQL
                    # any error aborts the whole transaction and would undo the
                    # CREATE TABLE. A savepoint confines the damage to the one
                    # statement that failed.
                    cur.execute('SAVEPOINT hb_stmt')
                try:
                    cur.execute(translated, params)
                except Exception:
                    if is_ddl:
                        try:
                            cur.execute('ROLLBACK TO SAVEPOINT hb_stmt')
                            # The savepoint already put the transaction back in a
                            # usable state. Rolling the whole thing back here
                            # would undo the CREATE TABLEs that ran earlier in
                            # this same transaction - which is exactly what the
                            # savepoint exists to prevent.
                            savepoint_restored = True
                        except Exception:
                            pass
                    raise
                if is_ddl:
                    cur.execute('RELEASE SAVEPOINT hb_stmt')
        except Exception as exc:
            if not savepoint_restored:
                try:
                    self._pg.rollback()
                except Exception:
                    pass
            raise _translate_error(exc) from exc

        cursor = Cursor(self, cur, sql)
        cursor.description = cur.description
        try:
            cursor.rowcount = cur.rowcount
        except Exception:
            pass

        if want_id:
            try:
                row = cur.fetchone()
                if row:
                    cursor.lastrowid = row[0]
                    cursor._insert_id_row = row
            except Exception:
                cursor.lastrowid = None

        return cursor

    def executemany(self, sql, seq_of_params):
        cur = self.execute(sql, ())
        for params in seq_of_params:
            self.execute(sql, params)
        return cur

    def executescript(self, script):
        for stmt in _split_statements(script):
            self.execute(stmt)

    def cursor(self, *args, **kwargs):
        """A DBAPI cursor that still schema-qualifies statements.

        Used by ``pandas.read_sql_query``, which grabs a cursor and calls
        ``execute()`` itself - so it would otherwise bypass the translator and
        resolve bare table names through ``search_path``, which the -pooler host
        (PgBouncer, transaction pooling) does not preserve between transactions.
        """
        return RawCursor(self, self._pg.cursor(*args, **kwargs))

    def commit_on_close(self):
        pass

    # -- internals ----------------------------------------------------------
    def _columns(self):
        """{table: {column}} for this schema (cached, refreshed by DDL).

        One catalog query replaces the per-statement ``information_schema``
        lookups that deciding whether a guarded ``ADD COLUMN`` is a no-op would
        otherwise need. That matters because the app issues dozens of them at
        import and each round trip through Neon's pooler costs about a second.
        """
        if self._all_cols is not None:
            return self._all_cols
        cur = self._pg.cursor()
        try:
            cur.execute(
                """
                SELECT table_name, column_name
                FROM information_schema.columns
                WHERE table_schema = %s
                """,
                (self.schema,),
            )
            cols = {}
            for table, column in cur.fetchall():
                cols.setdefault(table.lower(), set()).add(column.lower())
            self._all_cols = cols
        except Exception:
            self._pg.rollback()
            self._all_cols = {}
        finally:
            cur.close()
        return self._all_cols

    def _indexes(self):
        """Lower-cased index names in this schema (cached, refreshed by DDL)."""
        if self._index_names is not None:
            return self._index_names
        cur = self._pg.cursor()
        try:
            cur.execute(
                """
                SELECT indexname
                FROM pg_indexes
                WHERE schemaname = %s
                """,
                (self.schema,),
            )
            self._index_names = {r[0].lower() for r in cur.fetchall()}
        except Exception:
            self._pg.rollback()
            self._index_names = set()
        finally:
            cur.close()
        return self._index_names

    def _is_noop_ddl(self, sql):
        """True when a guarded DDL statement provably changes nothing.

        ``CREATE TABLE IF NOT EXISTS`` for a table the catalog already lists,
        ``ADD COLUMN IF NOT EXISTS`` for a column the table already has, and
        ``CREATE INDEX IF NOT EXISTS`` for an index that exists are guaranteed
        no-ops in PostgreSQL. Answering those from the cache instead of sending
        them is semantically identical, and it is the difference between a
        network round trip each and nothing at all.

        Returns False whenever there is any doubt, so an unrecognised or
        unguarded statement always reaches the server.
        """
        statement = sql.strip()
        if not statement:
            return False

        match = _CREATE_INDEX_NAME_RE.match(statement)
        if match:
            if not _IF_NOT_EXISTS_RE.search(statement):
                return False
            name = (match.group('name') or match.group('bare') or '').lower()
            return bool(name) and self._index_names is not None and name in self._index_names

        match = _CREATE_TABLE_NAME_RE.match(statement) or _CREATE_TABLE_NAME_UNQUALIFIED_RE.match(statement)
        if match:
            if not _IF_NOT_EXISTS_RE.search(statement):
                return False
            name = (match.group('name') or match.group('bare') or '').lower()
            return bool(name) and self._table_names is not None and name in self._table_names

        match = _ADD_COLUMN_NAME_RE.match(statement)
        if match:
            if not _IF_NOT_EXISTS_RE.search(statement):
                return False
            column = (match.group('name') or match.group('bare') or '').lower()
            table = _alter_target_table(statement)
            if not column or not table:
                return False
            existing = self._columns().get(table)
            return existing is not None and column in existing

        return False

    def _all_statements_noop(self, sql):
        """True when every statement in ``sql`` is a provable no-op.

        The translator turns ``ALTER TABLE ... ADD COLUMN c TEXT UNIQUE`` into two
        statements (the ALTER plus a companion unique index). Skipping the pair
        is only safe when *both* halves are already satisfied, so each statement
        is checked on its own.
        """
        parts = [p for p in _split_statements(sql) if p.strip()]
        if not parts:
            return False
        return all(self._is_noop_ddl(part) for part in parts)

    def _tables(self):
        """Lower-cased table names in this schema (cached, cleared by DDL)."""
        if self._table_names is not None:
            return self._table_names
        cur = self._pg.cursor()
        try:
            cur.execute(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = %s
                """,
                (self.schema,),
            )
            self._table_names = {r[0].lower() for r in cur.fetchall()}
        except Exception:
            self._pg.rollback()
            self._table_names = set()
        finally:
            cur.close()
        return self._table_names

    def _boolean_columns(self):
        """Names of BOOLEAN columns in this schema (cached, refreshed on DDL)."""
        if self._bool_cols is not None:
            return self._bool_cols
        cur = self._pg.cursor()
        try:
            cur.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = %s AND data_type = 'boolean'
                """,
                (self.schema,),
            )
            self._bool_cols = {r[0] for r in cur.fetchall()}
        except Exception:
            self._pg.rollback()
            self._bool_cols = set()
        finally:
            cur.close()
        return self._bool_cols

    def _prepare_insert(self, sql, params):
        """Append RETURNING id to INSERTs so ``cursor.lastrowid`` works."""
        m = _INSERT_RE.match(sql)
        if not m:
            return sql, params, False
        if 'RETURNING' in sql.upper():
            return sql, params, False
        table = _unqualify(m.group(1))
        if not self._has_id_column(table):
            return sql, params, False
        stripped = sql.rstrip()
        if stripped.endswith(';'):
            stripped = stripped[:-1]
        return stripped + ' RETURNING id', params, True

    def _has_id_column(self, table):
        """Cached check for whether a table has a plain ``id`` column."""
        if table in self._id_columns:
            return self._id_columns[table]
        cur = self._pg.cursor()
        try:
            cur.execute(
                """
                SELECT a.attname
                FROM pg_attribute a
                JOIN pg_class c ON c.oid = a.attrelid
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = %s AND c.relname = %s
                  AND a.attname = 'id' AND a.attnum > 0 AND NOT a.attisdropped
                """,
                (self.schema, table.lower()),
            )
            found = cur.fetchone() is not None
        except Exception:
            # This lookup is only an optimisation; never let it break an INSERT.
            self._pg.rollback()
            found = False
        finally:
            cur.close()
        self._id_columns[table] = found
        return found

    @staticmethod
    def _ensure_schema(dsn, schema):
        """Create every schema the app maps to, over a single connection.

        Connecting to Neon is expensive: the ``-pooler`` endpoint adds a few
        seconds per handshake, and a free-tier compute that has just woken from
        suspension adds more. Opening a throwaway connection per schema doubled
        the connection count - and so the startup time - for no benefit, because
        ``CREATE SCHEMA IF NOT EXISTS`` is idempotent and can create them all in
        one pass the first time anything connects. After that first call this is
        just an in-memory set lookup.

        The statements are sent as one batched execute for the same reason: a
        round trip through the pooler costs about a second, and five separate
        CREATE SCHEMA statements cost five of them.
        """
        if schema in _created_schemas:
            return

        missing = sorted({schema, *SCHEMA_MAP.values()} - _created_schemas)
        statements = '; '.join(
            f'CREATE SCHEMA IF NOT EXISTS "{name}"' for name in missing
        )
        with _get_psycopg().connect(dsn, **{**_connect_kwargs(), 'autocommit': True}) as pg:
            with pg.cursor() as cur:
                cur.execute(statements)
        _created_schemas.update(missing)


# --------------------------------------------------------------------------- #
# Connection pool
# --------------------------------------------------------------------------- #
# The app opens a connection for nearly every operation (62 call sites across the
# nine data modules). Opening a real socket each time would exhaust Neon's
# connection limit, so each schema keeps one live connection that is handed out
# repeatedly and returned by close().

_pool = {}


def _acquire(dsn, schema):
    """Return the shared connection for ``schema``, creating it if needed."""
    conn = _pool.get(schema)
    if conn is not None and not conn._pg.closed:
        try:
            # Never hand out a connection that is mid-aborted-transaction.
            if conn._pg.info.transaction_status != _get_pg_status_idle():
                conn._pg.rollback()
        except Exception:
            conn = None
        else:
            # Callers set row_factory right after connecting (or not at all), so
            # reset it - otherwise one module's setting leaks into the next caller.
            conn.row_factory = None
            conn._shared = True
            return conn

    conn = _open_with_retry(dsn, schema)
    conn._shared = True
    _pool[schema] = conn
    return conn


def _open_with_retry(dsn, schema):
    """Open a pooled connection, retrying a few times on a transient failure.

    A suspended free-tier Neon instance or a briefly unavailable pooler refuses
    the first connection for a second or two, and because the app opens a
    connection per schema during import that single blip would abort startup.
    Retries are bounded and only cover the *connect*; once a connection exists,
    statement handling is governed by the read-only retry in Connection.execute.
    """
    attempts = _int_env('HB_DB_CONNECT_ATTEMPTS', 3)
    delay = _int_env('HB_DB_CONNECT_RETRY_DELAY', 1.5)

    last = None
    for attempt in range(1, attempts + 1):
        try:
            return Connection(dsn, schema)
        except Exception as exc:
            last = exc
            if attempt == attempts:
                break
            _time.sleep(delay * attempt)

    raise last


def _release(schema, conn):
    """Return a pooled connection, rolling back any dangling transaction."""
    if _pool.get(schema) is conn:
        try:
            if conn._pg.info.transaction_status != _get_pg_status_idle():
                conn._pg.rollback()
        except Exception:
            _pool[schema] = None
    try:
        conn._shared = False
    except Exception:
        pass


def _split_statements(script):
    """Split a multi-statement script on semicolons outside literals."""
    chunks = _split_literals(script)
    parts, current = [], []
    for is_lit, text in chunks:
        if is_lit:
            current.append(text)
        else:
            buf = []
            for ch in text:
                if ch == ';':
                    stmt = ''.join(current + buf).strip()
                    if stmt:
                        parts.append(stmt)
                    current, buf = [], []
                else:
                    buf.append(ch)
            current.append(''.join(buf))
    tail = ''.join(current).strip()
    if tail:
        parts.append(tail)
    return parts


# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #

def connect(db_file=None, *args, **kwargs):
    """Open a connection, mirroring ``sqlite3.connect()``.

    Returns a :class:`Connection` bound to the PostgreSQL schema that matches
    ``db_file``, or a genuine ``sqlite3`` connection when ``HB_DB_BACKEND=sqlite``.

    PostgreSQL connections are pooled per schema. The calling code keeps doing
    ``conn.close()`` exactly as it always did; that simply returns the
    connection to the pool instead of tearing down a socket.
    """
    url = _database_url()
    if _force_sqlite() or not url:
        return _sqlite3.connect(db_file or ':memory:')
    schema = _schema_for(db_file) if db_file else DEFAULT_SCHEMA
    return _acquire(url, schema)


def server_version():
    """Return the connected PostgreSQL server version string.

    Queried lazily on first call. Nothing in the app asks for it - the schema
    setup used to fetch it eagerly, which cost an extra round trip through the
    pooler on every fresh process to fill in a value no code read.
    """
    global _server_version
    if _server_version is None:
        url = _database_url()
        if _force_sqlite() or not url:
            return None
        try:
            with _get_psycopg().connect(url, **{**_connect_kwargs(), 'autocommit': True}) as pg:
                with pg.cursor() as cur:
                    cur.execute('SHOW server_version')
                    _server_version = cur.fetchone()[0]
        except Exception:
            return None
    return _server_version


def is_postgres():
    """True when connections are being served by PostgreSQL."""
    return bool(_database_url()) and not _force_sqlite()


def close_all():
    """Close every pooled connection. Call this on application shutdown."""
    for schema in list(_pool):
        conn = _pool[schema]
        _pool[schema] = None
        if conn is not None:
            try:
                conn._pg.close()
            except Exception:
                pass


# Re-exported so modules can do ``from db import sqlite3`` if they prefer.
# Row and the exception names above are already module globals; ``from db import
# Row`` works without any help from here.
sqlite3 = _sqlite3
